sudo:     required
dist:     trusty
language: cpp

services:
  - docker

script:
- docker build .

branches:
  only:
    - master

notifications:
  recipients:
    - u.scholz83@gmx.de
  email:
    on_success: change
    on_failure: always

os:
  - linux
